version: "3.9"

services:
  app:
    container_name: nest-api
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    ports:
      - 2999:2999
    command: yarn run start
    env_file:
      - .env
    networks:
      - webnet
    restart: unless-stopped
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:14
    networks:
      - webnet
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
networks:
  webnet:
volumes:
  pgdata:
